version: "2"
services:
  db:
    image: mysql
    container_name: db
    networks:
      - backend
    environment:
      MYSQL_ROOT_PASSWORD: pass
    ports:
      - 3306:3306
    expose:
      - 3306
    volumes:
      - ./sql/schema.sql:/docker-entrypoint-initdb.d/1.sql
      - db_data:/database
    restart: always

  web_app:
    build: .
    container_name: burrito_app
    networks:
      - backend
    ports:
      - 8080:8080
    expose:
      - 8080
    environment:
      DATABASE_HOST: db
      MYSQL_HOST: db
      MYSQL_PORT: 3306
      MYSQL_USER: "root"
      MYSQL_PASSWORD: "pass"
      MYSQL_DATABASE: "burritoDB"
    depends_on:
      - db
    restart: always
    command: npm start

volumes:
  db_data:

networks:
  backend:
